version: '3'
services:
  docqa:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_docs:/app/uploaded_docs
      - ./vectorstores:/app/vectorstores
    environment:
      - OPENAI_API_KEY=